### ISSUE TITLE
Auth handler error

### ISSUE THREAD

**Issue by ostorc** [fit-ctu-discord/honza-botner#204]
```
Message:
The given key '625412337633067019' was not present in the dictionary.
Stack Trace:
at System.Collections.Concurrent.ConcurrentDictionary2.ThrowKeyNotFoundException(TKey key)
   at System.Collections.Concurrent.ConcurrentDictionary2.get_Item(TKey key)
at HonzaBotner.Discord.Services.EventHandlers.VerificationEventHandler.Handle(ComponentInteractionCreateEventArgs eventArgs) in /tmp/build_867415ea/src/HonzaBotner.Discord.Services/EventHandlers/VerificationEventHandler.cs:line 38
at HonzaBotner.Discord.EventHandler.EventHandler.Handle[T](T eventArgs) in /tmp/build_8674...
```
This error is now being thrown quite often (as seen in logs channel)

Maybe @stepech could help, since he was the last one to touch this area.

**Comment by ostorc** [comment]
https://github.com/fit-ctu-discord/honza-botner/blob/b48ff5fb29b23314b6d5c7e79b58c490a7901f28/src/HonzaBotner.Discord.Services/EventHandlers/VerificationEventHandler.cs#L38
Maybe replace this line with something like:
```csharp
DiscordMember member = await eventArgs.Guild.GetMemberAsync(user.Id);
```
